name: Run tests

on:
  push:
    branches: [main]
    
jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install server dependencies
        uses: bahmutov/npm-install@v1
        with:
          workin-directory: server
      - name: Install web dependencies
        uses: bahmutov/npm-install@v1
        with:
          workin-directory: web
      - name: Component & API & UI Tests
        uses: cypress-io/github-action@2.9.1
        with:
          working-directory: web
          install: false
          start: npm run start:ci
          wait-on: 'http://localhost:3000'
